services:
  - type: web
    name: face-value-backend
    env: python
    plan: free
    region: oregon
    branch: backend
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:8000

