services:
  - type: web
    name: face-value-backend
    env: python
    plan: free
    branch: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars: []
